# Generated by Django 3.1.1 on 2020-09-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.TextField(max_length=1000)),
                ('calories', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ingredients',
            },
        ),
    ]
